
import type { Tool } from '@/lib/types';

export const aiBackgroundRemovalTools: Tool[] = [
    { name: 'Remove.bg', description: 'Remove image backgrounds in 5 seconds.', url: 'https://www.remove.bg/', image: 'https://www.google.com/s2/favicons?sz=128&domain=remove.bg', dataAiHint: 'background remover', pricing: 'Freemium' },
    { name: 'PhotoRoom', description: 'Create product pictures & remove backgrounds.', url: 'https://www.photoroom.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photoroom.com', dataAiHint: 'product photos', pricing: 'Freemium' },
    { name: 'Slazzer', description: 'Instantly remove background from any image.', url: 'https://www.slazzer.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=slazzer.com', dataAiHint: 'cutout tool', pricing: 'Freemium' },
    { name: 'Erase.bg', description: 'Free background image remover.', url: 'https://www.erase.bg/', image: 'https://www.google.com/s2/favicons?sz=128&domain=erase.bg', dataAiHint: 'free background remover', pricing: 'Free' },
    { name: 'Cutout.pro', description: 'AI-powered background remover and photo editor.', url: 'https://www.cutout.pro/', image: 'https://www.google.com/s2/favicons?sz=128&domain=cutout.pro', dataAiHint: 'ai cutout', pricing: 'Freemium' },
    { name: 'Canva Background Remover', description: 'Remove the background of any image with one click.', url: 'https://www.canva.com/pro/background-remover/', image: 'https://www.google.com/s2/favicons?sz=128&domain=canva.com', dataAiHint: 'one-click remover', pricing: 'Paid' },
    { name: 'Fotor Background Remover', description: 'Free online tool to make image backgrounds transparent.', url: 'https://www.fotor.com/features/background-remover', image: 'https://www.google.com/s2/favicons?sz=128&domain=fotor.com', dataAiHint: 'transparent background', pricing: 'Freemium' },
    { name: 'Pixlr BG Remover', description: 'AI-powered background remover.', url: 'https://pixlr.com/remove-background/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixlr.com', dataAiHint: 'pixlr bg', pricing: 'Freemium' },
    { name: 'Adobe Express BG Remover', description: 'Free tool to remove backgrounds.', url: 'https://www.adobe.com/express/feature/image/remove-background', image: 'https://www.google.com/s2/favicons?sz=128&domain=adobe.com', dataAiHint: 'express bg', pricing: 'Free' },
    { name: 'Pixelcut', description: 'Remove the background from any photo for free.', url: 'https://www.pixelcut.ai/background-remover', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixelcut.ai', dataAiHint: 'ai graphic designer', pricing: 'Freemium' },
    { name: 'Removal.ai', description: 'AI tool to remove background from images.', url: 'https://removal.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=removal.ai', dataAiHint: 'bulk remover', pricing: 'Freemium' },
    { name: 'Depositphotos BG Remover', description: 'Free background remover.', url: 'https://depositphotos.com/bgremover.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=depositphotos.com', dataAiHint: 'stock photo', pricing: 'Free' },
    { name: 'inPixio', description: 'Remove backgrounds from photos.', url: 'https://www.inpixio.com/remove-background/', image: 'https://www.google.com/s2/favicons?sz=128&domain=inpixio.com', dataAiHint: 'photo studio', pricing: 'Freemium' },
    { name: 'Clipping Magic', description: 'Easily remove background online.', url: 'https://clippingmagic.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=clippingmagic.com', dataAiHint: 'image clipping', pricing: 'Paid' },
    { name: 'PhotoScissors', description: 'Automatically remove background from images.', url: 'https://photoscissors.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photoscissors.com', dataAiHint: 'online remover', pricing: 'Freemium' },
    { name: 'Retoucher.online', description: 'Free online background remover.', url: 'https://retoucher.online/background-remover', image: 'https://www.google.com/s2/favicons?sz=128&domain=retoucher.online', dataAiHint: 'free online', pricing: 'Free' },
    { name: 'AutoClipping', description: 'Free online background remover.', url: 'https://autoclipping.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=autoclipping.com', dataAiHint: 'auto clipping', pricing: 'Free' },
    { name: 'Wondershare PixCut', description: 'AI background remover and photo editor.', url: 'https://pixcut.wondershare.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=wondershare.com', dataAiHint: 'wondershare tool', pricing: 'Freemium' },
    { name: 'Apowersoft BG Remover', description: 'One-click background remover.', url: 'https://www.apowersoft.com/background-eraser', image: 'https://www.google.com/s2/favicons?sz=128&domain=apowersoft.com', dataAiHint: 'one click', pricing: 'Paid' },
    { name: 'SocialBook BG Remover', description: 'Free AI background remover.', url: 'https://socialbook.io/tools/background-remover', image: 'https://www.google.com/s2/favicons?sz=128&domain=socialbook.io', dataAiHint: 'youtube tools', pricing: 'Free' }
];
