
import type { Tool } from '@/lib/types';

export const aiColorCorrectionGradingTools: Tool[] = [
    { name: 'Palette.fm', description: 'AI colorizer for black and white photos.', url: 'https://palette.fm/', image: 'https://www.google.com/s2/favicons?sz=128&domain=palette.fm', dataAiHint: 'photo colorizer', pricing: 'Freemium' },
    { name: 'Colorize.cc', description: 'AI to colorize your black and white photos.', url: 'https://colorize.cc/', image: 'https://www.google.com/s2/favicons?sz=128&domain=colorize.cc', dataAiHint: 'colorize black white', pricing: 'Freemium' },
    { name: 'Img2Go Colorize', description: 'Colorize black and white images online for free.', url: 'https://www.img2go.com/colorize-image', image: 'https://www.google.com/s2/favicons?sz=128&domain=img2go.com', dataAiHint: 'free colorize', pricing: 'Free' },
    { name: 'Hotpot.ai AI Colorizer', description: 'AI to colorize black and white photos.', url: 'https://hotpot.ai/colorize-picture', image: 'https://www.google.com/s2/favicons?sz=128&domain=hotpot.ai', dataAiHint: 'picture colorizer', pricing: 'Freemium' },
    { name: 'DeepAI Image Colorization', description: 'Colorize black and white images.', url: 'https://deepai.org/machine-learning-model/colorizer', image: 'https://www.google.com/s2/favicons?sz=128&domain=deepai.org', dataAiHint: 'ml colorizer', pricing: 'Freemium' },
    { name: 'MyHeritage In Color', description: 'Colorize your black and white photos.', url: 'https://www.myheritage.com/incolor', image: 'https://www.google.com/s2/favicons?sz=128&domain=myheritage.com', dataAiHint: 'family photos', pricing: 'Freemium' },
    { name: 'VanceAI Photo Colorizer', description: 'Colorize photos with AI.', url: 'https://vanceai.com/photo-colorizer/', image: 'https://www.google.com/s2/favicons?sz=128&domain=vanceai.com', dataAiHint: 'ai colorizer', pricing: 'Freemium' },
    { name: 'Colourise.com', description: 'Colorize photos online.', url: 'https://colourise.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=colourise.com', dataAiHint: 'online colorize', pricing: 'Free' },
    { name: 'Algorithmia Image Colorization', description: 'API for image colorization.', url: 'https://algorithmia.com/algorithms/deeplearning/ColorfulImageColorization', image: 'https://www.google.com/s2/favicons?sz=128&domain=algorithmia.com', dataAiHint: 'developer api', pricing: 'Paid' },
    { name: 'DeOldify', description: 'A deep learning based model for colorizing and restoring old images.', url: 'https://github.com/jantic/DeOldify', image: 'https://www.google.com/s2/favicons?sz=128&domain=github.com', dataAiHint: 'open source', pricing: 'Free' },
    { name: 'Photomyne Colorize', description: 'Colorize your scanned B&W photos.', url: 'https://photomyne.com/colorize-photos', image: 'https://www.google.com/s2/favicons?sz=128&domain=photomyne.com', dataAiHint: 'photo scan', pricing: 'Freemium' },
    { name: 'CODIJY', description: 'Photo colorization software.', url: 'https://codijy.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=codijy.com', dataAiHint: 'colorization software', pricing: 'Paid' },
    { name: 'Adobe Photoshop Neural Filters', description: 'Colorize filter for black and white images.', url: 'https://www.adobe.com/products/photoshop.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=adobe.com', dataAiHint: 'neural filters', pricing: 'Paid' },
    { name: 'Luminar Neo', description: 'Color correction and enhancement tools.', url: 'https://skylum.com/luminar', image: 'https://www.google.com/s2/favicons?sz=128&domain=skylum.com', dataAiHint: 'color enhance', pricing: 'Paid' },
    { name: 'DxO PhotoLab', description: 'Advanced color correction and grading.', url: 'https://www.dxo.com/dxo-photolab/', image: 'https://www.google.com/s2/favicons?sz=128&domain=dxo.com', dataAiHint: 'color grading', pricing: 'Paid' },
    { name: 'Capture One Pro', description: 'Professional color grading tools.', url: 'https://www.captureone.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=captureone.com', dataAiHint: 'pro color', pricing: 'Paid' },
    { name: 'Final Cut Pro Color Grading', description: 'Advanced color grading for video.', url: 'https://www.apple.com/final-cut-pro/', image: 'https://www.google.com/s2/favicons?sz=128&domain=apple.com', dataAiHint: 'video color', pricing: 'Paid' },
    { name: 'DaVinci Resolve', description: 'The standard for color correction.', url: 'https://www.blackmagicdesign.com/products/davinciresolve', image: 'https://www.google.com/s2/favicons?sz=128&domain=blackmagicdesign.com', dataAiHint: 'hollywood color', pricing: 'Freemium' },
    { name: 'Colourlab.ai', description: 'AI-powered color grading.', url: 'https://www.colourlab.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=colourlab.ai', dataAiHint: 'ai grading', pricing: 'Paid' },
    { name: 'Color.io', description: 'Online photo & video color grading.', url: 'https://color.io/', image: 'https://www.google.com/s2/favicons?sz=128&domain=color.io', dataAiHint: '3d luts', pricing: 'Paid' }
];
