
import type { Tool } from '@/lib/types';

export const aiFaceEnhancementSkinRetouchTools: Tool[] = [
    { name: 'FaceApp', description: 'AI face editor with filters and transformations.', url: 'https://www.faceapp.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=faceapp.com', dataAiHint: 'face filter', pricing: 'Freemium' },
    { name: 'YouCam Makeup', description: 'Virtual makeup and skin diagnostics.', url: 'https://www.perfectcorp.com/consumer/apps/ymk', image: 'https://www.google.com/s2/favicons?sz=128&domain=perfectcorp.com', dataAiHint: 'virtual makeup', pricing: 'Freemium' },
    { name: 'Fotor Skin Retouch', description: 'Retouch portraits with AI-powered tools.', url: 'https://www.fotor.com/features/touch-up', image: 'https://www.google.com/s2/favicons?sz=128&domain=fotor.com', dataAiHint: 'skin retouch', pricing: 'Freemium' },
    { name: 'PortraitPro', description: 'Specialized in skin smoothing and blemish removal.', url: 'https://www.anthropics.com/portraitpro/', image: 'https://www.google.com/s2/favicons?sz=128&domain=anthropics.com', dataAiHint: 'skin smoothing', pricing: 'Paid' },
    { name: 'AirBrush', description: 'Remove blemishes, smooth skin, and whiten teeth.', url: 'https://airbrush.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=airbrush.com', dataAiHint: 'blemish remover', pricing: 'Freemium' },
    { name: 'Facetune', description: 'Selfie editor with skin smoothing and face shaping tools.', url: 'https://www.facetuneapp.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=facetuneapp.com', dataAiHint: 'face shape', pricing: 'Freemium' },
    { name: 'Luminar Neo', description: 'Skin AI and Face AI tools for automated retouching.', url: 'https://skylum.com/luminar', image: 'https://www.google.com/s2/favicons?sz=128&domain=skylum.com', dataAiHint: 'skin ai', pricing: 'Paid' },
    { name: 'PhotoDiva', description: 'Free portrait editor with skin retouching features.', url: 'https://photodiva.net/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photodiva.net', dataAiHint: 'pc portrait', pricing: 'Free' },
    { name: 'Remini', description: 'Enhance faces and skin details in photos.', url: 'https://remini.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=remini.ai', dataAiHint: 'face detail', pricing: 'Freemium' },
    { name: 'Evoto AI', description: 'Advanced skin retouching with frequency separation.', url: 'https://www.evoto.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=evoto.ai', dataAiHint: 'frequency separation', pricing: 'Freemium' },
    { name: 'BeautyPlus', description: 'Retouch skin and apply makeup effects.', url: 'https://www.beautyplus.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=beautyplus.com', dataAiHint: 'makeup effects', pricing: 'Freemium' },
    { name: 'Meitu', description: 'AI-powered beauty camera and photo editor.', url: 'https://www.meitu.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=meitu.com', dataAiHint: 'beauty editor', pricing: 'Freemium' },
    { name: 'Perfect365', description: 'One-tap makeup and face retouching.', url: 'https://perfect365.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=perfect365.com', dataAiHint: 'one-tap makeup', pricing: 'Freemium' },
    { name: 'VanceAI Portrait Retoucher', description: 'Blemish remover and skin smoother.', url: 'https://vanceai.com/portrait-retoucher/', image: 'https://www.google.com/s2/favicons?sz=128&domain=vanceai.com', dataAiHint: 'ai retoucher', pricing: 'Freemium' },
    { name: 'fixthephoto', description: 'Online tool to remove blemishes.', url: 'https://fixthephoto.com/face-blemish-remover.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=fixthephoto.com', dataAiHint: 'online blemish', pricing: 'Free' },
    { name: 'piZap', description: 'Wrinkle remover, blemish fix, and more.', url: 'https://www.pizap.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pizap.com', dataAiHint: 'wrinkle remover', pricing: 'Freemium' },
    { name: 'Photopea', description: 'Online editor with advanced healing tools.', url: 'https://www.photopea.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photopea.com', dataAiHint: 'healing brush', pricing: 'Free' },
    { name: 'Picsart', description: 'Retouch selfies with AI face tools.', url: 'https://picsart.com/face-retouch', image: 'https://www.google.com/s2/favicons?sz=128&domain=picsart.com', dataAiHint: 'ai face tools', pricing: 'Freemium' },
    { name: 'Snapseed', description: 'Mobile app with portrait enhancement tools.', url: 'https://snapseed.online/', image: 'https://www.google.com/s2/favicons?sz=128&domain=snapseed.online', dataAiHint: 'mobile retouch', pricing: 'Free' },
    { name: 'Wink', description: 'Quality-enhancing video and photo editor.', url: 'https://wink.meitu.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=wink.meitu.com', dataAiHint: 'video retouch', pricing: 'Freemium' }
];
