
import type { Tool } from '@/lib/types';

export const aiImageEnhancementUpscalerTools: Tool[] = [
    { name: 'Topaz Photo AI', description: 'Maximize image quality on autopilot.', url: 'https://www.topazlabs.com/topaz-photo-ai', image: 'https://www.google.com/s2/favicons?sz=128&domain=topazlabs.com', dataAiHint: 'image upscaler', pricing: 'Paid' },
    { name: 'Let\'s Enhance', description: 'AI image enlarger & upscaler.', url: 'https://letsenhance.io/', image: 'https://www.google.com/s2/favicons?sz=128&domain=letsenhance.io', dataAiHint: 'image sharpener', pricing: 'Freemium' },
    { name: 'Remini', description: 'AI photo and video enhancer.', url: 'https://remini.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=remini.ai', dataAiHint: 'photo enhancer', pricing: 'Freemium' },
    { name: 'VanceAI', description: 'Suite of AI photo enhancement tools.', url: 'https://vanceai.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=vanceai.com', dataAiHint: 'photo quality', pricing: 'Freemium' },
    { name: 'Bigjpg', description: 'AI image enlarger for anime and illustrations.', url: 'https://bigjpg.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=bigjpg.com', dataAiHint: 'anime upscale', pricing: 'Freemium' },
    { name: 'Gigapixel AI', description: 'Enlarge and enhance your images.', url: 'https://www.topazlabs.com/gigapixel-ai', image: 'https://www.google.com/s2/favicons?sz=128&domain=topazlabs.com', dataAiHint: 'photo enlargement', pricing: 'Paid' },
    { name: 'Zyro AI Image Upscaler', description: 'Free image upscaler.', url: 'https://zyro.com/tools/image-upscaler', image: 'https://www.google.com/s2/favicons?sz=128&domain=zyro.com', dataAiHint: 'free upscaler', pricing: 'Free' },
    { name: 'AI. Image Enlarger', description: 'Upscale and enhance images for free.', url: 'https://imglarger.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=imglarger.com', dataAiHint: 'image enlarger', pricing: 'Freemium' },
    { name: 'Deep-Image.ai', description: 'AI image upscaler and enhancer.', url: 'https://deep-image.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=deep-image.ai', dataAiHint: 'batch processing', pricing: 'Freemium' },
    { name: 'Waifu2x', description: 'Image scaling and noise reduction for anime-style art.', url: 'http://waifu2x.udp.jp/', image: 'https://www.google.com/s2/favicons?sz=128&domain=waifu2x.udp.jp', dataAiHint: 'anime scaler', pricing: 'Free' },
    { name: 'Icons8 Smart Upscaler', description: 'Enlarge images without losing quality.', url: 'https://icons8.com/upscaler', image: 'https://www.google.com/s2/favicons?sz=128&domain=icons8.com', dataAiHint: 'smart upscaler', pricing: 'Freemium' },
    { name: 'Stockphotos.com AI Upscaler', description: 'Free image upscaler.', url: 'https://www.stockphotos.com/upscaler', image: 'https://www.google.com/s2/favicons?sz=128&domain=stockphotos.com', dataAiHint: 'photo upscaler', pricing: 'Free' },
    { name: 'AVCLabs Photo Enhancer AI', description: 'AI Photo Enhancement Software.', url: 'https://www.avclabs.com/photo-enhancer-ai.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=avclabs.com', dataAiHint: 'desktop software', pricing: 'Paid' },
    { name: 'PhotoRefiner', description: 'Japanese AI-powered image enhancement service.', url: 'https://ja.photorefiner.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photorefiner.com', dataAiHint: 'japanese ai', pricing: 'Paid' },
    { name: 'Fotor Photo Enhancer', description: 'One-tap enhance your photo quality.', url: 'https://www.fotor.com/features/one-tap-enhance', image: 'https://www.google.com/s2/favicons?sz=128&domain=fotor.com', dataAiHint: 'one-tap enhance', pricing: 'Freemium' },
    { name: 'HitPaw Photo Enhancer', description: 'AI-powered image quality enhancer.', url: 'https://www.hitpaw.com/photo-enhancer.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=hitpaw.com', dataAiHint: '4k upscaler', pricing: 'Paid' },
    { name: 'Media.io Image Upscaler', description: 'Upscale images online for free.', url: 'https://www.media.io/image-upscaler.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=media.io', dataAiHint: 'online upscaler', pricing: 'Freemium' },
    { name: 'Pixelcut Image Upscaler', description: 'Upscale and enhance photos for free.', url: 'https://www.pixelcut.ai/image-upscaler', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixelcut.ai', dataAiHint: 'hd photos', pricing: 'Freemium' },
    { name: 'Cutout.pro Image Upscaler', description: 'AI image upscaler and enhancer.', url: 'https://www.cutout.pro/image-enhancer-upscaler', image: 'https://www.google.com/s2/favicons?sz=128&domain=cutout.pro', dataAiHint: 'pro upscaler', pricing: 'Freemium' },
    { name: 'Img.Upscaler', description: 'AI image upscaler based on the latest AI technology.', url: 'https://imgupscaler.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=imgupscaler.com', dataAiHint: 'latest ai', pricing: 'Freemium' }
];
