
import type { Tool } from '@/lib/types';

export const aiImageToImageEditingTools: Tool[] = [
    { name: 'Stable Diffusion (img2img)', description: 'Transform images with text prompts.', url: 'https://stablediffusionweb.com/img2img', image: 'https://www.google.com/s2/favicons?sz=128&domain=stablediffusionweb.com', dataAiHint: 'image transform', pricing: 'Free' },
    { name: 'Playground AI', description: 'Remix and edit images with text.', url: 'https://playground.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=playground.com', dataAiHint: 'image remix', pricing: 'Freemium' },
    { name: 'Artbreeder', description: 'Create and breed images by mixing them.', url: 'https://www.artbreeder.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=artbreeder.com', dataAiHint: 'image mixing', pricing: 'Freemium' },
    { name: 'Midjourney Variations', description: 'Create variations of an existing Midjourney image.', url: 'https://docs.midjourney.com/docs/variations', image: 'https://www.google.com/s2/favicons?sz=128&domain=docs.midjourney.com', dataAiHint: 'image variations', pricing: 'Paid' },
    { name: 'KREA AI', description: 'Real-time image enhancement and generation.', url: 'https://www.krea.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=krea.ai', dataAiHint: 'real-time enhance', pricing: 'Freemium' },
    { name: 'Recraft AI', description: 'AI tool for generating and editing vector art.', url: 'https://www.recraft.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=recraft.ai', dataAiHint: 'vector art', pricing: 'Freemium' },
    { name: 'Runway ML Image Editing', description: 'A suite of AI magic tools for image manipulation.', url: 'https://runwayml.com/image-editing/', image: 'https://www.google.com/s2/favicons?sz=128&domain=runwayml.com', dataAiHint: 'magic tools', pricing: 'Freemium' },
    { name: 'Clipdrop', description: 'An ecosystem of apps, plugins & resources for all creators.', url: 'https://clipdrop.co/', image: 'https://www.google.com/s2/favicons?sz=128&domain=clipdrop.co', dataAiHint: 'remove background', pricing: 'Freemium' },
    { name: 'Ebsynth', description: 'Bring paintings to life.', url: 'https://ebsynth.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=ebsynth.com', dataAiHint: 'video synthesis', pricing: 'Free' },
    { name: 'PaintsChainer', description: 'AI-powered automatic colorization of line art.', url: 'https://paintschainer.preferred.tech/index_en.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=paintschainer.preferred.tech', dataAiHint: 'line art colorization', pricing: 'Free' },
    { name: 'Petalica Paint', description: 'Automatic coloring for line drawings.', url: 'https://petalica-paint.pixiv.dev/', image: 'https://www.google.com/s2/favicons?sz=128&domain=petalica-paint.pixiv.dev', dataAiHint: 'pixiv ai', pricing: 'Free' },
    { name: 'Scribble Diffusion', description: 'Turn your sketch into a refined image.', url: 'https://scribblediffusion.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=scribblediffusion.com', dataAiHint: 'sketch to image', pricing: 'Free' },
    { name: 'Reface', description: 'Face swap videos and GIFs.', url: 'https://reface.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=reface.ai', dataAiHint: 'video face swap', pricing: 'Freemium' },
    { name: 'Faceswapper.ai', description: 'Free online face swapper.', url: 'https://www.faceswapper.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=faceswapper.ai', dataAiHint: 'online face swap', pricing: 'Free' },
    { name: 'Runway Motion Brush', description: 'Add controlled motion to still images.', url: 'https://runwayml.com/motion-brush/', image: 'https://www.google.com/s2/favicons?sz=128&domain=runwayml.com', dataAiHint: 'image animation', pricing: 'Freemium' },
    { name: 'LeiaPix Converter', description: 'Convert 2D images to 3D lightfield images.', url: 'https://convert.leiapix.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=convert.leiapix.com', dataAiHint: '3d photo', pricing: 'Free' },
    { name: 'D-ID Creative Reality', description: 'Create videos from a single image.', url: 'https://www.d-id.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=d-id.com', dataAiHint: 'talking photos', pricing: 'Freemium' },
    { name: 'Vizcom', description: 'Bring your drawings to life in seconds.', url: 'https://www.vizcom.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=vizcom.ai', dataAiHint: 'design rendering', pricing: 'Freemium' },
    { name: 'Genmo', description: 'Create videos from images and text prompts.', url: 'https://www.genmo.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=genmo.ai', dataAiHint: 'generative video', pricing: 'Freemium' },
    { name: 'Kaiber', description: 'Transform your images into stunning videos.', url: 'https://www.kaiber.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=kaiber.ai', dataAiHint: 'visual storytelling', pricing: 'Freemium' }
];
