
import type { Tool } from '@/lib/types';

export const aiObjectRemovalTools: Tool[] = [
    { name: 'Magic Eraser', description: 'Remove unwanted things from images in seconds.', url: 'https://www.magiceraser.io/', image: 'https://www.google.com/s2/favicons?sz=128&domain=magiceraser.io', dataAiHint: 'object remover', pricing: 'Freemium' },
    { name: 'Inpaint', description: 'Remove objects from your photos.', url: 'https://theinpaint.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=theinpaint.com', dataAiHint: 'photo restoration', pricing: 'Paid' },
    { name: 'Cleanup.pictures', description: 'Remove any unwanted object, defect, people or text.', url: 'https://cleanup.pictures/', image: 'https://www.google.com/s2/favicons?sz=128&domain=cleanup.pictures', dataAiHint: 'remove defect', pricing: 'Freemium' },
    { name: 'Hama', description: 'Erase anything from your photos online.', url: 'https://www.hama.app/', image: 'https://www.google.com/s2/favicons?sz=128&domain=hama.app', dataAiHint: 'online eraser', pricing: 'Free' },
    { name: 'Fotor Object Remover', description: 'Remove unwanted objects from photos for free.', url: 'https://www.fotor.com/features/object-remover', image: 'https://www.google.com/s2/favicons?sz=128&domain=fotor.com', dataAiHint: 'free remover', pricing: 'Freemium' },
    { name: 'Cutout.pro Object Remover', description: 'Remove unwanted objects, people, or watermarks.', url: 'https://www.cutout.pro/remove-object', image: 'https://www.google.com/s2/favicons?sz=128&domain=cutout.pro', dataAiHint: 'watermark remover', pricing: 'Freemium' },
    { name: 'PicWish Photo Eraser', description: 'Free AI object remover.', url: 'https://picwish.com/photo-eraser', image: 'https://www.google.com/s2/favicons?sz=128&domain=picwish.com', dataAiHint: 'ai eraser', pricing: 'Free' },
    { name: 'Adobe Photoshop Content-Aware Fill', description: 'Remove unwanted objects from your images.', url: 'https://www.adobe.com/products/photoshop.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=adobe.com', dataAiHint: 'content-aware', pricing: 'Paid' },
    { name: 'TouchRetouch', description: 'App for removing unwanted content from photos.', url: 'https://adva-soft.com/touch-retouch/', image: 'https://www.google.com/s2/favicons?sz=128&domain=adva-soft.com', dataAiHint: 'photo retouch', pricing: 'Paid' },
    { name: 'PhotoRoom Magic Retouch', description: 'Erase any object from your picture.', url: 'https://www.photoroom.com/magic-retouch', image: 'https://www.google.com/s2/favicons?sz=128&domain=photoroom.com', dataAiHint: 'magic retouch', pricing: 'Freemium' },
    { name: 'YouCam Perfect', description: 'AI Object Remover to clean up photos.', url: 'https://www.perfectcorp.com/consumer/apps/ycp', image: 'https://www.google.com/s2/favicons?sz=128&domain=perfectcorp.com', dataAiHint: 'selfie editor', pricing: 'Freemium' },
    { name: 'Canva Magic Eraser', description: 'Remove unwanted objects from photos.', url: 'https://www.canva.com/pro/magic-eraser/', image: 'https://www.google.com/s2/favicons?sz=128&domain=canva.com', dataAiHint: 'design tool', pricing: 'Paid' },
    { name: 'SnapEdit', description: 'AI-powered photo editing app.', url: 'https://snapedit.app/', image: 'https://www.google.com/s2/favicons?sz=128&domain=snapedit.app', dataAiHint: 'mobile editor', pricing: 'Freemium' },
    { name: 'ZMO.AI Remover', description: 'Remove unwanted things from photos.', url: 'https://www.zmo.ai/remover/', image: 'https://www.google.com/s2/favicons?sz=128&domain=zmo.ai', dataAiHint: 'ai tools', pricing: 'Freemium' },
    { name: 'HitPaw Watermark Remover', description: 'Remove watermarks from photos and videos.', url: 'https://www.hitpaw.com/watermark-remover.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=hitpaw.com', dataAiHint: 'watermark remover', pricing: 'Paid' },
    { name: 'Aiseesoft Free Watermark Remover', description: 'Remove any watermark from your photos online.', url: 'https://www.aiseesoft.com/free-watermark-remover-online/', image: 'https://www.google.com/s2/favicons?sz=128&domain=aiseesoft.com', dataAiHint: 'free watermark', pricing: 'Free' },
    { name: 'WatermarkRemover.io', description: 'Remove watermarks from your images for free.', url: 'https://www.watermarkremover.io/', image: 'https://www.google.com/s2/favicons?sz=128&domain=watermarkremover.io', dataAiHint: 'remove watermarks', pricing: 'Free' },
    { name: 'Snapseed Healing Tool', description: 'Mobile app tool to remove unwanted objects.', url: 'https://snapseed.online/', image: 'https://www.google.com/s2/favicons?sz=128&domain=snapseed.online', dataAiHint: 'mobile healing', pricing: 'Free' },
    { name: 'Pixomatic Magic Object Eraser', description: 'Remove unwanted objects with a tap.', url: 'https://pixomatic.us/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixomatic.us', dataAiHint: 'photo editor app', pricing: 'Freemium' },
    { name: 'Luminar Neo Erase Tool', description: 'AI-powered object removal.', url: 'https://skylum.com/luminar', image: 'https://www.google.com/s2/favicons?sz=128&domain=skylum.com', dataAiHint: 'erase tool', pricing: 'Paid' }
];
