
import type { Tool } from '@/lib/types';

export const aiPhotoRestorationTools: Tool[] = [
    { name: 'MyHeritage Photo Tools', description: 'Colorize, enhance, and animate old photos.', url: 'https://www.myheritage.com/photo-enhancer', image: 'https://www.google.com/s2/favicons?sz=128&domain=myheritage.com', dataAiHint: 'old photos', pricing: 'Freemium' },
    { name: 'Hotpot.ai', description: 'AI tools for colorizing and restoring old photos.', url: 'https://hotpot.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=hotpot.ai', dataAiHint: 'photo restore', pricing: 'Freemium' },
    { name: 'VanceAI Photo Restorer', description: 'Remove scratches and restore old photos.', url: 'https://vanceai.com/photo-restorer/', image: 'https://www.google.com/s2/favicons?sz=128&domain=vanceai.com', dataAiHint: 'scratch removal', pricing: 'Freemium' },
    { name: 'Remini', description: 'AI photo and video enhancer for old photos.', url: 'https://remini.ai/', image: 'https://www.google.com/s2/favicons?sz=128&domain=remini.ai', dataAiHint: 'photo enhancer', pricing: 'Freemium' },
    { name: 'Fotor Photo Restoration', description: 'AI photo restoration to fix old photos.', url: 'https://www.fotor.com/features/photo-restoration', image: 'https://www.google.com/s2/favicons?sz=128&domain=fotor.com', dataAiHint: 'fix old photos', pricing: 'Freemium' },
    { name: 'ImgUpscaler Old Photo Restoration', description: 'Restore old portrait photos online for free.', url: 'https://imgupscaler.com/old-photo-restoration', image: 'https://www.google.com/s2/favicons?sz=128&domain=imgupscaler.com', dataAiHint: 'free restoration', pricing: 'Free' },
    { name: 'PhotoMyne', description: 'Scan old photos and slides.', url: 'https://www.photomyne.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photomyne.com', dataAiHint: 'photo scanner', pricing: 'Freemium' },
    { name: 'AKVIS Retoucher', description: 'Photo restoration software.', url: 'https://akvis.com/en/retoucher/index.php', image: 'https://www.google.com/s2/favicons?sz=128&domain=akvis.com', dataAiHint: 'retouching software', pricing: 'Paid' },
    { name: 'RestorePhotos.io', description: 'Free AI old photo restoration.', url: 'https://www.restorephotos.io/', image: 'https://www.google.com/s2/favicons?sz=128&domain=restorephotos.io', dataAiHint: 'ai restoration', pricing: 'Free' },
    { name: 'PhotoGlory', description: 'Software to restore old photos.', url: 'https://photoglory.net/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photoglory.net', dataAiHint: 'photo software', pricing: 'Paid' },
    { name: 'Inpaint', description: 'Remove defects from old photos.', url: 'https://theinpaint.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=theinpaint.com', dataAiHint: 'defect removal', pricing: 'Paid' },
    { name: 'Deep Nostalgia', description: 'Animate the faces in your family photos.', url: 'https://www.myheritage.com/deep-nostalgia', image: 'https://www.google.com/s2/favicons?sz=128&domain=myheritage.com', dataAiHint: 'animate photos', pricing: 'Freemium' },
    { name: 'Basepaws', description: 'AI tool for restoring old pet photos.', url: 'https://basepaws.com/products/pet-photo-restoration', image: 'https://www.google.com/s2/favicons?sz=128&domain=basepaws.com', dataAiHint: 'pet photos', pricing: 'Paid' },
    { name: 'Pho.to', description: 'Online photo editor with vintage effects.', url: 'https://pho.to/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pho.to', dataAiHint: 'vintage effects', pricing: 'Free' },
    { name: 'Reimagine', description: 'AI photo enhancer and colorizer by MyHeritage.', url: 'https://www.myheritage.com/reimagine', image: 'https://www.google.com/s2/favicons?sz=128&domain=myheritage.com', dataAiHint: 'ai enhancer', pricing: 'Freemium' },
    { name: 'Neural.love', description: 'AI Image Restore & Enhance.', url: 'https://neural.love/image-restore', image: 'https://www.google.com/s2/favicons?sz=128&domain=neural.love', dataAiHint: 'image restore', pricing: 'Freemium' },
    { name: 'Pixelup', description: 'AI Photo Enhancer & Unblur.', url: 'https://pixelup.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixelup.com', dataAiHint: 'unblur photo', pricing: 'Freemium' },
    { name: 'Phowd', description: 'Professional photo retouching service.', url: 'https://www.phowd.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=phowd.com', dataAiHint: 'retouching service', pricing: 'Paid' },
    { name: 'Weedit.photos', description: 'Old photo restoration services.', url: 'https://weedit.photos/old-photo-restoration-services/', image: 'https://www.google.com/s2/favicons?sz=128&domain=weedit.photos', dataAiHint: 'restoration service', pricing: 'Paid' },
    { name: 'ScanCafe', description: 'Photo scanning and restoration services.', url: 'https://www.scancafe.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=scancafe.com', dataAiHint: 'scanning service', pricing: 'Paid' }
];
