
import type { Tool } from '@/lib/types';

export const aiPhotoEditorTools: Tool[] = [
    { name: 'Adobe Photoshop', description: 'Industry standard with AI features like Generative Fill.', url: 'https://www.adobe.com/products/photoshop.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=adobe.com', dataAiHint: 'ai editor', pricing: 'Paid' },
    { name: 'Luminar Neo', description: 'AI-powered photo editor for stunning results.', url: 'https://skylum.com/luminar', image: 'https://www.google.com/s2/favicons?sz=128&domain=skylum.com', dataAiHint: 'photo ai', pricing: 'Paid' },
    { name: 'Fotor', description: 'All-in-one online photo editor with AI.', url: 'https://www.fotor.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=fotor.com', dataAiHint: 'online editor', pricing: 'Freemium' },
    { name: 'Canva', description: 'Online design tool with AI photo editing features.', url: 'https://www.canva.com/photo-editor/', image: 'https://www.google.com/s2/favicons?sz=128&domain=canva.com', dataAiHint: 'design editor', pricing: 'Freemium' },
    { name: 'Pixlr', description: 'Free online photo editor with AI tools.', url: 'https://pixlr.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixlr.com', dataAiHint: 'free editor', pricing: 'Freemium' },
    { name: 'Topaz Photo AI', description: 'Maximize image quality on autopilot.', url: 'https://www.topazlabs.com/topaz-photo-ai', image: 'https://www.google.com/s2/favicons?sz=128&domain=topazlabs.com', dataAiHint: 'image upscaler', pricing: 'Paid' },
    { name: 'GIMP', description: 'Free & open source image editor.', url: 'https://www.gimp.org/', image: 'https://www.google.com/s2/favicons?sz=128&domain=gimp.org', dataAiHint: 'open source', pricing: 'Free' },
    { name: 'Affinity Photo', description: 'Professional image editing software.', url: 'https://affinity.serif.com/en-us/photo/', image: 'https://www.google.com/s2/favicons?sz=128&domain=affinity.serif.com', dataAiHint: 'photoshop alternative', pricing: 'Paid' },
    { name: 'Movavi Photo Editor', description: 'Photo editing software for PC.', url: 'https://www.movavi.com/photo-editor/', image: 'https://www.google.com/s2/favicons?sz=128&domain=movavi.com', dataAiHint: 'pc editor', pricing: 'Paid' },
    { name: 'BeFunky', description: 'Online Photo Editor, Collage Maker, and Graphic Designer.', url: 'https://www.befunky.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=befunky.com', dataAiHint: 'collage maker', pricing: 'Freemium' },
    { name: 'Picsart', description: 'Suite of online photo and video editing tools.', url: 'https://picsart.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=picsart.com', dataAiHint: 'creative tools', pricing: 'Freemium' },
    { name: 'Photopea', description: 'Free online editor supporting PSD, XCF, Sketch, XD and CDR formats.', url: 'https://www.photopea.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=photopea.com', dataAiHint: 'psd editor', pricing: 'Free' },
    { name: 'CyberLink PhotoDirector', description: 'AI-powered creative photo editor.', url: 'https://www.cyberlink.com/products/photodirector-photo-editing-software/features_en_US.html', image: 'https://www.google.com/s2/favicons?sz=128&domain=cyberlink.com', dataAiHint: 'creative editor', pricing: 'Freemium' },
    { name: 'ON1 Photo RAW', description: 'The ultimate all-in-one photo editor.', url: 'https://www.on1.com/products/photo-raw/', image: 'https://www.google.com/s2/favicons?sz=128&domain=on1.com', dataAiHint: 'raw editor', pricing: 'Paid' },
    { name: 'Corel PaintShop Pro', description: 'Professional photo editing software.', url: 'https://www.paintshoppro.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=paintshoppro.com', dataAiHint: 'pro photo', pricing: 'Paid' },
    { name: 'Polarr', description: 'Advanced photo editor with pro filters.', url: 'https://polarr.co/', image: 'https://www.google.com/s2/favicons?sz=128&domain=polarr.co', dataAiHint: 'photo filters', pricing: 'Freemium' },
    { name: 'ACDSee Photo Studio', description: 'Creative photo editing and management.', url: 'https://www.acdsee.com/en/products/photo-studio-ultimate/', image: 'https://www.google.com/s2/favicons?sz=128&domain=acdsee.com', dataAiHint: 'dam software', pricing: 'Paid' },
    { name: 'Pixelmator Pro', description: 'Professional image editor for Mac.', url: 'https://www.pixelmator.com/pro/', image: 'https://www.google.com/s2/favicons?sz=128&domain=pixelmator.com', dataAiHint: 'mac editor', pricing: 'Paid' },
    { name: 'DxO PhotoLab', description: 'Advanced photo editing software.', url: 'https://www.dxo.com/dxo-photolab/', image: 'https://www.google.com/s2/favicons?sz=128&domain=dxo.com', dataAiHint: 'raw processing', pricing: 'Paid' },
    { name: 'Capture One Pro', description: 'Photo editing software for professionals.', url: 'https://www.captureone.com/', image: 'https://www.google.com/s2/favicons?sz=128&domain=captureone.com', dataAiHint: 'tethered shooting', pricing: 'Paid' }
];
